//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hospital()
        {
            this.User = new HashSet<User>();
        }
    
        public int CodeMed { get; set; }
        public string FullName { get; set; }
        public string SmallName { get; set; }
        public string NameSubjectRussia { get; set; }
        public int CodePostal { get; set; }
        public string AddressMed { get; set; }
        public string PhoneMed { get; set; }
        public string MailMed { get; set; }
        public string LicenseNumber { get; set; }
        public System.DateTime LicenseDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
